let vehicles=getVehicles();const $=id=>document.getElementById(id);
function render(){vehicles=getVehicles();$("adminList").innerHTML=vehicles.length?vehicles.map(v=>`<article class="admin-car"><img src="${v.image}" alt=""><div><small>${v.brand} · ${v.year}</small><h3>${v.model} ${v.variant}</h3><p>${v.price} · ${v.colour} · ${v.branch}</p></div><div class="admin-actions"><button onclick="editCar('${v.id}')">EDIT</button><button class="danger" onclick="deleteCar('${v.id}')">DELETE</button></div></article>`).join(""):`<p>No vehicles. Add one using the form.</p>`}
function clearForm(){$("vehicleForm").reset();$("year").value=2026;$("mileage").value="0 km";$("editId").value="";$("formTitle").textContent="Add vehicle";$("cancelEdit").style.display="none"}
$("vehicleForm").onsubmit=e=>{e.preventDefault();const id=$("editId").value||("v"+Date.now());const car={id,brand:$("brand").value,model:$("model").value.trim(),variant:$("variant").value.trim(),year:Number($("year").value),price:$("price").value.trim(),colour:$("colour").value.trim(),mileage:$("mileage").value.trim(),branch:$("branch").value,image:$("image").value.trim(),engine:$("engine").value.trim(),power:$("power").value.trim(),torque:$("torque").value.trim(),transmission:$("transmission").value.trim(),features:$("features").value.split(",").map(x=>x.trim()).filter(Boolean),description:$("description").value.trim()};const i=vehicles.findIndex(v=>v.id===id);if(i>=0)vehicles[i]=car;else vehicles.unshift(car);saveVehicles(vehicles);$("adminMessage").textContent="Vehicle saved. The main website will use the updated list in this browser.";clearForm();render()}
window.editCar=id=>{const v=vehicles.find(x=>x.id===id);if(!v)return;["brand","model","variant","year","price","colour","mileage","branch","image","engine","power","torque","transmission","description"].forEach(k=>$(k).value=v[k]??"");$("features").value=(v.features||[]).join(", ");$("editId").value=v.id;$("formTitle").textContent="Edit vehicle";$("cancelEdit").style.display="inline-flex";scrollTo({top:0,behavior:"smooth"})}
window.deleteCar=id=>{if(!confirm("Delete this vehicle from the mockup?"))return;vehicles=vehicles.filter(v=>v.id!==id);saveVehicles(vehicles);render()}
$("cancelEdit").onclick=clearForm;$("resetDemo").onclick=()=>{if(confirm("Reset all mockup vehicle changes?")){localStorage.removeItem("kelstonVehicles");vehicles=getVehicles();clearForm();render()}};clearForm();render();

$("logoutBtn").onclick=()=>{sessionStorage.removeItem("kelstonAdminLoggedIn");location.replace("login.html")};
