const FALLBACK="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1800&q=90";
const defaultModels=[
{brand:"OMODA",model:"C5",price:"From R339 900",image:"https://www.secondsonline.co.za/images/1000/vehicles/260416/1244089-2.jpg"},
{brand:"JAECOO",model:"J5",price:"From R339 900",image:"https://www.omodajaecoo-digicars.co.za/_next/image?q=90&url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Fpekrroqi%2Fproduction%2F0f5e407c61b04f4f8ed4f63f316280418215a6ef-3718x2480.jpg&w=3840"},
{brand:"OMODA",model:"C7",price:"From R539 900",image:"https://www.omodajaecoo-digicars.co.za/_next/image?q=90&url=%2F_next%2Fstatic%2Fmedia%2Fbanner17.316393e1.jpg&w=3840"},
{brand:"JAECOO",model:"J7",price:"From R549 900",image:"https://i0.wp.com/theauto.page/wp-content/uploads/2024/11/Jaecoo-J7-1.jpg?fit=1200%2C800&ssl=1"},
{brand:"OMODA",model:"C9",price:"From R785 900",image:"https://lepas-digicars.co.za/assets/images/2025-MATTEGREY-OMODA-C9-20T-Inspire-8773483-1-1200x900-1.webp"}
];
function getVehicles(){try{const x=JSON.parse(localStorage.getItem("kelstonVehicles"));return Array.isArray(x)&&x.length?x:DEFAULTS}catch(e){return DEFAULTS}}
const DEFAULTS=[
{id:"c7",brand:"OMODA",model:"C7",variant:"Elegance",year:2026,price:"R589 900",colour:"Moonlight Silver",mileage:"0 km",branch:"Gqeberha",image:"https://www.omodajaecoo-digicars.co.za/_next/image?q=90&url=%2F_next%2Fstatic%2Fmedia%2Fbanner17.316393e1.jpg&w=3840",engine:"1.6 TGDI",power:"145 kW",torque:"290 Nm",transmission:"7DCT",features:["15.6-inch infotainment","Panoramic sunroof","Wireless CarPlay & Android Auto","540° panoramic camera"],description:"Bold geometry, premium comfort and intelligent technology in a modern crossover."},
{id:"j5",brand:"JAECOO",model:"J5",variant:"Vortex",year:2026,price:"R379 900",colour:"Model Green",mileage:"0 km",branch:"Gqeberha",image:"https://www.omodajaecoo-digicars.co.za/_next/image?q=90&url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Fpekrroqi%2Fproduction%2F0f5e407c61b04f4f8ed4f63f316280418215a6ef-3718x2480.jpg&w=3840",engine:"1.5 Turbo",power:"115 kW",torque:"230 Nm",transmission:"CVT",features:["LED lighting","Digital cockpit","Driver assistance","Premium interior"],description:"Compact, confident and designed for everyday versatility."},
{id:"j7",brand:"JAECOO",model:"J7",variant:"Glacier",year:2026,price:"R579 900",colour:"Khaki White",mileage:"0 km",branch:"Jeffreys Bay",image:"https://i0.wp.com/theauto.page/wp-content/uploads/2024/11/Jaecoo-J7-1.jpg?fit=1200%2C800&ssl=1",engine:"1.6 TGDI",power:"145 kW",torque:"290 Nm",transmission:"7DCT",features:["Panoramic roof","Large touchscreen","Advanced safety","Premium cabin"],description:"A rugged luxury SUV with clean lines and confident road presence."},
{id:"c9",brand:"OMODA",model:"C9",variant:"Inspire",year:2026,price:"R785 900",colour:"Matte Grey",mileage:"0 km",branch:"Gqeberha",image:"https://lepas-digicars.co.za/assets/images/2025-MATTEGREY-OMODA-C9-20T-Inspire-8773483-1-1200x900-1.webp",engine:"2.0 TGDI",power:"192 kW",torque:"400 Nm",transmission:"8-speed automatic",features:["Luxury seating","Premium audio","Panoramic roof","Advanced driver assistance"],description:"OMODA's flagship SUV combines performance with a refined, technology-focused cabin."}
];
let vehicles=getVehicles();
function modelCard(m){return `<article class="model-card reveal" data-brand="${m.brand}"><img src="${m.image}" alt="${m.brand} ${m.model}" onerror="this.src='${FALLBACK}'"><div class="model-copy"><small>${m.brand}</small><h3>${m.model}</h3><p>${m.price}</p></div></article>`}
function renderModels(filter="all"){modelGrid.innerHTML=defaultModels.filter(m=>filter==="all"||m.brand===filter).map(modelCard).join("");observe()}
function vehicleCard(v){return `<article class="vehicle-card reveal" data-id="${v.id}" tabindex="0"><div class="vehicle-pic"><img src="${v.image}" alt="${v.brand} ${v.model} ${v.colour}" onerror="this.src='${FALLBACK}'"><span>VIEW DETAILS</span></div><div class="vehicle-info"><div class="meta">${v.year} · ${v.colour} · ${v.mileage}</div><h3>${v.brand} ${v.model} ${v.variant}</h3><strong>${v.price}</strong><div class="vehicle-bottom"><span>${v.branch}</span><b>EXPLORE →</b></div></div></article>`}
function renderVehicles(){vehicles=getVehicles();vehicleGrid.innerHTML=vehicles.map(vehicleCard).join("");modelSelect.innerHTML=vehicles.map(v=>`<option>${v.brand} ${v.model} ${v.variant}</option>`).join("");document.querySelectorAll(".vehicle-card").forEach(c=>{c.onclick=()=>openVehicle(c.dataset.id);c.onkeydown=e=>{if(e.key==="Enter")openVehicle(c.dataset.id)}});observe()}
function openVehicle(id){const v=vehicles.find(x=>x.id===id);if(!v)return;modalContent.innerHTML=`<div class="detail-image"><img src="${v.image}" alt="${v.brand} ${v.model}" onerror="this.src='${FALLBACK}'"></div><div class="detail-copy"><p class="eyebrow dark">${v.brand} · ${v.year}</p><h2>${v.model} <span>${v.variant}</span></h2><div class="detail-price">${v.price}</div><p>${v.description||""}</p><div class="detail-specs"><div><small>ENGINE</small><strong>${v.engine||"—"}</strong></div><div><small>POWER</small><strong>${v.power||"—"}</strong></div><div><small>TORQUE</small><strong>${v.torque||"—"}</strong></div><div><small>TRANSMISSION</small><strong>${v.transmission||"—"}</strong></div><div><small>COLOUR</small><strong>${v.colour}</strong></div><div><small>LOCATION</small><strong>${v.branch}</strong></div></div><h4>Highlights</h4><ul>${(v.features||[]).map(f=>`<li>${f}</li>`).join("")}</ul><a class="btn submit" href="#test-drive" onclick="closeModal()">BOOK A TEST DRIVE</a></div>`;vehicleModal.classList.add("open");vehicleModal.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll")}
function closeModal(){vehicleModal.classList.remove("open");vehicleModal.setAttribute("aria-hidden","true");document.body.classList.remove("no-scroll")}
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=closeModal);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderModels(b.dataset.filter)});
function observe(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.06});document.querySelectorAll(".reveal:not(.visible)").forEach(x=>o.observe(x))}
renderModels();renderVehicles();observe();
addEventListener("scroll",()=>topbar.classList.toggle("scrolled",scrollY>40));menuBtn.onclick=()=>mobileMenu.classList.toggle("open");document.querySelectorAll("#mobileMenu a").forEach(a=>a.onclick=()=>mobileMenu.classList.remove("open"));
leadForm.onsubmit=e=>{e.preventDefault();formNote.textContent="Mockup only — form submission is not connected yet."};
